### ISSUE TITLE
Get a list of wikilinks defined in a file

### ISSUE THREAD

**Issue by aldrichtr** [aldrichtr/PSDendron#12]
A wikilink is the _edge_ in a graph of the vault.  It is a From->To relation of two _nodes_, so it has:
- **From** : The Node the link is _in_
- **To** : The Node that is the _target_ of the link

## Wiki link

Additionally, dendron provides a few pieces of metadata to a wikilink:

- **(display)Name** : This is "alternate text" to be displayed instead of the node name
  For example, `cardinal` in:
  ```markdown
  [[cardinal|resource.birds.cardinalidae]]
  ```
- **Heading** : a link can identify a specific heading within the document
  - the heading is placed after the "target" with a '#' token, like
    ```markdown
    [[cardinal|resource.birds.cardinalidae#Habitat]]
    ```
- **Block** : any point in a file can be "marked" with a '^' and a name, which creates an `anchor`.  you can then add the named anchor in the target like:
  ```markdown
  [[cardinal|resource.birds.cardinalidae#^grossbeak]]
  ```

## Note Reference

In dendron, if the wikilink is preceded by an '!', then the link is a [Note Reference](https://wiki.dendron.so/notes/f1af56bb-db27-47ae-8406-61a98de6c78c/) which allows you to "include" the content of the linked node in the presentation (either the previewer or the published page).

a Note Reference:
- Has the `To` node (which can include a wildcard character like `![[log.daily.2022.06.*]]`
- does not use the `Name` field (although it is not an error to add one)
- Can have a Heading field
- Can have a Block field
- Adds a Range Reference.  This is the range of content that is included in the view

### Range Reference

the syntax is `![[note#start#end]]` where `start` 

- can be a heading or a block reference
- can include a `line offset` which skips the given number of lines.  syntax `,{number}`

And `end`

- can be a heading or a block reference
- can be a "wildcard header" syntax `#*` which tells dendron to include all lines up until the next header

## Tasks

- [ ] Identify the type of link.  Wiki Link or Note Reference depending on the presence of a '!'
- [ ] Have a `From` Property that records the node and line
- [ ] Have a `To` Property that records the node (and potentially the start and end line)
